"""create site content table

Revision ID: 3c6b4b217ef3
Revises: 
Create Date: 2026-01-15 17:31:02.477008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6b4b217ef3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admission_process_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_code')
    )
    op.create_table('cuet_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=1), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code')
    )
    op.create_table('important_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('benefit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('full_form', sa.String(length=300), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('filled_seats', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('merit_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('reservation_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('domicile', sa.String(length=100), nullable=True),
    sa.Column('applicable_for', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counselling_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('total_male', sa.Integer(), nullable=True),
    sa.Column('total_female', sa.Integer(), nullable=True),
    sa.Column('filled_male', sa.Integer(), nullable=True),
    sa.Column('filled_female', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_cuet_subjects',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['cuet_subjects.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'subject_id')
    )
    op.create_table('cutoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('closing_rank', sa.Integer(), nullable=True),
    sa.Column('admitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('program_type', sa.String(length=10), nullable=True),
    sa.Column('tuition_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('development_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exam_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fees')
    op.drop_table('cutoffs')
    op.drop_table('course_cuet_subjects')
    op.drop_table('counselling_seats')
    op.drop_table('reservation_policy')
    op.drop_table('merit_rules')
    op.drop_table('courses')
    op.drop_table('site_content')
    op.drop_table('scholarships')
    op.drop_table('payment_modes')
    op.drop_table('important_instructions')
    op.drop_table('groups')
    op.drop_table('cuet_subjects')
    op.drop_table('categories')
    op.drop_table('admission_process_steps')
    op.drop_table('admins')
    # ### end Alembic commands ###
